import argparse

def parse():
    parser = argparse.ArgumentParser(description="Robotlab MLDL Training Tutorial 5 - Super Mario")
    parser.add_argument('--seed', type=int, default=3366, help='Set random seed')
    parser.add_argument('--world', type=int, default=1, help='Set a number in {1, 2, 3, 4, 5, 6, 7, 8} indicating the world')
    parser.add_argument('--stage', type=int, default=1, help='Set a number in {1, 2, 3, 4} indicating the stage within a world')
    parser.add_argument('--version', type=int, default=0, help='Set a number in {0, 1, 2, 3} specifying the ROM mode to use')
    parser.add_argument('--action_type', type=str, default='simple', help='Set mario action type in {right, simple, complex}')
    parser.add_argument('--num_skip_frame', type=int, default=4, help='Set number of environment skip frame')
    parser.add_argument('--downsample_rate', type=int, default=3, help='Set rate of environment downsample')
    parser.add_argument('--num_stack_frame', type=int, default=4, help='Set number of environment stack frame')
    parser.add_argument('--total_timestep', type=int, default=1200000, help='Set total training timestep')
    parser.add_argument('--max_step', type=int, default=1000, help='Set maximum of step')
    parser.add_argument('--step', type=int, default=512, help='Set number of steps to run for each environment')
    parser.add_argument('--episode', type=int, default=20, help='Set number of episode')
    parser.add_argument('--lr', type=float, default=5e-5, help='Set learning rate')
    parser.add_argument('--epoch', type=int, default=10, help='Set training epochs')
    parser.add_argument('--batchsize', type=int, default=128, help='Set training batchsize')
    parser.add_argument('--gamma', type=float, default=0.9, help='Set discount factor for rewards')
    parser.add_argument('--check_freq', type=int, default=10000, help='Set frequency to save model weight')
    parser.add_argument('--save_model_dir', type=str, default='./checkpoints/model', help='Path of saved model directory')
    parser.add_argument('--tensorboard', type=str, default='./checkpoints/tensorboard', help='Path of tensorboard')
    parser.add_argument('--output_video', type=str, default='./video', help='Path of output vidoe directory')

    return parser.parse_args()
